name: backstore
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.13
  mobile_scanner: ^3.0.0
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  graphql_flutter: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.10.0  


flutter:
  uses-material-design: true

  assets:
    - assets/svg/c.svg
    - assets/svg/o.svg
    - assets/svg/r.svg
    - assets/svg/o2.svg
    - assets/svg/n.svg
    - assets/svg/a.svg
    - assets/svg/registered.svg

flutter_icons:
  android: true
  ios: true
  web: false
  windows: false
  image_path: "assets/icons/corona_icon.png"  
  adaptive_icon_background: "#FCFBFF"         
  adaptive_icon_foreground: "assets/icons/corona_icon.png" 
